name: Create Discussion on New Issue

on:
  issues:
    types: [opened]

jobs:
  create_discussion:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'  # Adjust as needed
      - name: Get global node ID
        id: get-repo-id
        uses: nvdaes/get-repository-id@v1
        with:
          repository: ${{ github.repository }}

      - name: Run createDiscussion function
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_ID: ${{ steps.get-repo-id.outputs.repo-id }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          CATEGORY_ID: DIC_kwDOK8PX484Cgdqa
        run: node createDiscussion.ts  # Replace with the correct filename if different
