name: Create Discussion for Blog Issues

on:
  issues:
    types: [opened]
    tags:
      - blog

jobs:
  create-discussion:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install graphql request@^2.88.2

      - name: Create Discussion
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ISSUE_TITLE=$(jq -r '.issue.title' $GITHUB_EVENT_PATH)
          REPOSITORY_ID="R_kgDOK8PX4w"
          CATEGORY_ID="<OPTIONAL_CATEGORY_ID>"
          
          # Construct GraphQL query
          query='mutation {
            createDiscussion(input: {
              repositoryId: "'$REPOSITORY_ID'",
              categoryId: "DIC_kwDOK8PX484Cgdqa",
              body: "Discussion created based on issue: '$ISSUE_TITLE'",
              title: "'$ISSUE_TITLE'"
            }) {
              discussion {
                id
              }
            }
          }'
          
          # Send GraphQL request
          response=$(curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$(echo "$query" | jq -c .)" \
            https://api.github.com/graphql)
          
          echo "Discussion creation response:"
          echo "$response"
