name: Create Discussion on New Issue

on:
  issues:
    types: [opened]

jobs:
  create_discussion:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust as needed

      - name: Install dependencies
        run: pip install requests

      - name: Run maintenance script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_ID: ${{ steps.get-repo-id.outputs.repo-id }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          CATEGORY_ID: DIC_kwDOK8PX484Cgdqa
          VERCEL_REDEPLOY_HOOK: ${{ secrets.VERCEL_REDEPLOY_HOOK }}
        run: python maintenance.py
