name: Handle Issue add or delete

on:
  issues:
    types: [opened, deleted, edited]

jobs:
  handle_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Adjust as needed

      - name: Install dependencies
        run: pip install requests

      - name: Get global node ID
        id: get-repo-id
        uses: nvdaes/get-repository-id@v1
        with:
          repository: ${{ github.repository }}

      - name: Handle issue event
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY_ID: ${{ steps.get-repo-id.outputs.repo-id }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          CATEGORY_ID: ${{ vars.CATEGORY_ID}}
          VERCEL_REDEPLOY_HOOK: ${{ secrets.VERCEL_REDEPLOY_HOOK }}
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            python maintenance.py --add
          elif [ "${{ github.event.action }}" == "deleted" ]; then
            python maintenance.py --delete
          elif [ "${{ github.event.action }}" == "edited" ]; then
            python maintenance.py --update
          fi
